# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoGui01.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Virtual_AssistantUI(object):
    def setupUi(self, Virtual_AssistantUI):
        Virtual_AssistantUI.setObjectName("Virtual_AssistantUI")
        Virtual_AssistantUI.resize(1588, 1000)
        self.centralwidget = QtWidgets.QWidget(Virtual_AssistantUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gif_05 = QtWidgets.QLabel(self.centralwidget)
        self.gif_05.setGeometry(QtCore.QRect(0, 0, 1700, 1000))
        self.gif_05.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gif_05.setAutoFillBackground(True)
        self.gif_05.setText("")
        self.gif_05.setPixmap(QtGui.QPixmap("gifbackground.gif"))
        self.gif_05.setScaledContents(True)
        self.gif_05.setObjectName("gif_05")
        self.gif_01 = QtWidgets.QLabel(self.centralwidget)
        self.gif_01.setGeometry(QtCore.QRect(880, 10, 451, 271))
        self.gif_01.setText("")
        self.gif_01.setPixmap(QtGui.QPixmap("Virtual-Assistant-.gif"))
        self.gif_01.setScaledContents(True)
        self.gif_01.setObjectName("gif_01")
        self.gif_02 = QtWidgets.QLabel(self.centralwidget)
        self.gif_02.setGeometry(QtCore.QRect(310, 10, 281, 221))
        self.gif_02.setText("")
        self.gif_02.setPixmap(QtGui.QPixmap("circle.gif"))
        self.gif_02.setScaledContents(True)
        self.gif_02.setObjectName("gif_02")
        self.stopbutton = QtWidgets.QPushButton(self.centralwidget)
        self.stopbutton.setGeometry(QtCore.QRect(1180, 900, 171, 71))
        self.stopbutton.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 0);")
        self.stopbutton.setObjectName("stopbutton")
        self.startbutton = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(950, 900, 171, 71))
        self.startbutton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.startbutton.setObjectName("startbutton")
        self.exitbutton = QtWidgets.QPushButton(self.centralwidget)
        self.exitbutton.setGeometry(QtCore.QRect(1410, 900, 171, 71))
        self.exitbutton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.exitbutton.setObjectName("exitbutton")
        self.datetextbrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.datetextbrowser.setGeometry(QtCore.QRect(10, 10, 291, 71))
        self.datetextbrowser.setStyleSheet("background-color: transparent ;\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.datetextbrowser.setObjectName("datetextbrowser")
        self.timetextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.timetextBrowser.setGeometry(QtCore.QRect(10, 90, 291, 51))
        self.timetextBrowser.setStyleSheet("background-color: transparent ;\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.timetextBrowser.setObjectName("timetextBrowser")
        self.gif_04 = QtWidgets.QLabel(self.centralwidget)
        self.gif_04.setGeometry(QtCore.QRect(1130, 550, 451, 331))
        self.gif_04.setText("")
        self.gif_04.setPixmap(QtGui.QPixmap("gif05.gif"))
        self.gif_04.setScaledContents(True)
        self.gif_04.setObjectName("gif_04")
        self.gif_03 = QtWidgets.QLabel(self.centralwidget)
        self.gif_03.setGeometry(QtCore.QRect(1300, 40, 321, 551))
        self.gif_03.setText("")
        self.gif_03.setPixmap(QtGui.QPixmap("animated-television-image-0182.gif"))
        self.gif_03.setScaledContents(True)
        self.gif_03.setObjectName("gif_03")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 460, 121, 141))
        self.label_3.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 470, 101, 121))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("flowers.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 740, 451, 261))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("cartoon-cute.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        Virtual_AssistantUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(Virtual_AssistantUI)
        QtCore.QMetaObject.connectSlotsByName(Virtual_AssistantUI)

    def retranslateUi(self, Virtual_AssistantUI):
        _translate = QtCore.QCoreApplication.translate
        Virtual_AssistantUI.setWindowTitle(_translate("Virtual_AssistantUI", "MainWindow"))
        self.stopbutton.setText(_translate("Virtual_AssistantUI", "STOP"))
        self.startbutton.setText(_translate("Virtual_AssistantUI", "START"))
        self.exitbutton.setText(_translate("Virtual_AssistantUI", "EXIT"))
        self.datetextbrowser.setHtml(_translate("Virtual_AssistantUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Date</span></p></body></html>"))
        self.timetextBrowser.setHtml(_translate("Virtual_AssistantUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">Time</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Virtual_AssistantUI = QtWidgets.QMainWindow()
    ui = Ui_Virtual_AssistantUI()
    ui.setupUi(Virtual_AssistantUI)
    Virtual_AssistantUI.show()
    sys.exit(app.exec_())
